server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: kafka-listener

  kafka:
    template:
      default-topic: tacocloud.orders.topic
