server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: kafka-listener

  kafka:
    template:
      default-topic: tacocloud.orders.topic
#    consumer:
#      bootstrap-servers: localhost:9092
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: tacocloud_kitchen
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.rusted.packages: '*'
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: tacos

