server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: kafka-listener

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos
